### ISSUE TITLE
Lisibilité du projet suivant

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/standup#1]
Réduire la taille de la police du projet à suivre. Actuellement il s'affiche avec des "...".

**Comment by revolunet** [comment]
on parle de ce bouton : 

<img width="1058" alt="capture d ecran 2018-08-01 a 17 09 48" src="https://user-images.githubusercontent.com/124937/43530402-c18d4890-95ad-11e8-9429-2961cbef4a39.png">

**Comment by douglasduteil** [comment]
C'est fait ?

**Comment by douglasduteil** [comment]
Reopen if still relevant ;) @jrduscher @revolunet
